---
- name: Install
  yum: name=haproxy state=present

- name: Configure
  template: dest=/etc/haproxy/haproxy.cfg src=haproxy.cfg.j2 mode=0644
  notify: Restart haproxy

- name: Enable service
  service: name=haproxy state=started enabled=yes
