---
- name: Install
  yum: name={{item}} state=present
  with_items:
    - haproxy

- name: Configure
  template: dest=/etc/haproxy/haproxy.cfg src=haproxy.cfg.j2 mode=0644
  notify: Restart haproxy

- name: Enable service
  service: name=haproxy state=started enabled=yes
